name: Sync with Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: DocRuzzy/pioreactor_analysis_panel
          huggingface_repo_id: DocRuzzy/pioreactor_analysis_panel
          repo_type: space
          space_sdk: streamlit
          hf_token: ${{ secrets.HF_TOKEN }}